version: "3.9"

services:
  tests:
    build:
      context: .
      args:
        BASE_IMAGE: "python:3.9"
    image: mealieapi-tests:latest
    volumes:
      - ./volumes/coverage:/app/coverage:rw
    depends_on:
      - mealie-api
    environment:
      MEALIE_URL: http://mealie-api:9000
      MEALIE_TOKEN: ${MEALIE_TEST_SUITE_TOKEN}
    restart: unless-stopped
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5  # <-- Be diligent about updating this!!
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - API_PORT=9000
      - DEFAULT_GROUP="Testers"
      - DEFAULT_EMAIL="tester@email.com"
      - DEFAULT_PASSWORD="agloriouspasswordfortesting"
    restart: unless-stopped

volumes:
  mealie-data:
    driver: local
