name: Code Styling

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install workflow dependencies
        run: pip install poetry
      - name: Install Project Dependencies
        run: poetry install
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run isort
        run: isort mealieapi --check-only
      - name: Run black 
        run: black mealieapi --check
  typing:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install workflow dependencies
        run: pip install poetry
      - name: Install Project Dependencies
        run: poetry install --no-root
      - name: Run mypy
        run: mypy mealieapi
