name: Code Styling

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install workflow dependencies
        run: pip install poetry
      - name: Install Project Dependencies
        run: poetry install
      - name: Run flake8
        run: poetry run flake8 mealieapi
      - name: Run isort
        run: poetry run isort mealieapi --check-only
      - name: Run black 
        run: poetry run black mealieapi --check
  typing:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install workflow dependencies
        run: pip install poetry
      - name: Install Project Dependencies
        run: poetry install --no-root
      - name: Run mypy
        run: poetry run mypy mealieapi
