name: Flake8

on:
  pull_request:
  workflow_dispatch:

jobs:
  styling:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install workflow dependencies
        run: pip install flake8 isort black mypy
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: isort mealieapi --check-only
        name: Sort Codebase Imports
      - run: black mealieapi --check
        name: Lint Codebase
      - run: mypy mealieapi
        name: Check Codebase Type Annotations
  

    
